export interface UiStrings {
  subtitle: string;
  city: string;
  cityPlaceholder: string;
  householdSize: string;
  language: string;
  submit: string;
  submitting: string;
  fetchingForecast: string;
  generatingPlan: string;
  severity: string;
  travelAdvisory: string;
  before: string;
  during: string;
  after: string;
  checklist: string;
  safetyRecommendations: string;
}

const EN: UiStrings = {
  subtitle: "Real-time forecast, AI-personalized preparedness plans, in your language.",
  city: "City",
  cityPlaceholder: "e.g. Mumbai",
  householdSize: "Household size",
  language: "Language",
  submit: "Get preparedness plan",
  submitting: "Preparing your plan…",
  fetchingForecast: "Fetching forecast…",
  generatingPlan: "Generating your plan…",
  severity: "Severity",
  travelAdvisory: "Travel advisory",
  before: "Before",
  during: "During",
  after: "After",
  checklist: "Emergency checklist",
  safetyRecommendations: "Safety recommendations",
};

const UI_STRINGS: Record<string, UiStrings> = {
  English: EN,
  Hindi: {
    subtitle: "वास्तविक समय का पूर्वानुमान, आपकी भाषा में एआई-वैयक्तिकृत तैयारी योजनाएं।",
    city: "शहर",
    cityPlaceholder: "जैसे मुंबई",
    householdSize: "परिवार का आकार",
    language: "भाषा",
    submit: "तैयारी योजना प्राप्त करें",
    submitting: "आपकी योजना तैयार हो रही है…",
    fetchingForecast: "पूर्वानुमान प्राप्त हो रहा है…",
    generatingPlan: "आपकी योजना बनाई जा रही है…",
    severity: "गंभीरता",
    travelAdvisory: "यात्रा सलाह",
    before: "पहले",
    during: "दौरान",
    after: "बाद में",
    checklist: "आपातकालीन सूची",
    safetyRecommendations: "सुरक्षा सिफारिशें",
  },
  Bengali: {
    subtitle: "রিয়েল-টাইম পূর্বাভাস, আপনার ভাষায় এআই-ব্যক্তিগতকৃত প্রস্তুতি পরিকল্পনা।",
    city: "শহর",
    cityPlaceholder: "যেমন মুম্বাই",
    householdSize: "পরিবারের আকার",
    language: "ভাষা",
    submit: "প্রস্তুতি পরিকল্পনা পান",
    submitting: "আপনার পরিকল্পনা তৈরি হচ্ছে…",
    fetchingForecast: "পূর্বাভাস আনা হচ্ছে…",
    generatingPlan: "আপনার পরিকল্পনা তৈরি করা হচ্ছে…",
    severity: "তীব্রতা",
    travelAdvisory: "ভ্রমণ পরামর্শ",
    before: "আগে",
    during: "চলাকালীন",
    after: "পরে",
    checklist: "জরুরি চেকলিস্ট",
    safetyRecommendations: "নিরাপত্তা সুপারিশ",
  },
  Marathi: {
    subtitle: "रिअल-टाइम अंदाज, तुमच्या भाषेत एआय-वैयक्तिकृत तयारी योजना.",
    city: "शहर",
    cityPlaceholder: "उदा. मुंबई",
    householdSize: "कुटुंबाचा आकार",
    language: "भाषा",
    submit: "तयारी योजना मिळवा",
    submitting: "तुमची योजना तयार होत आहे…",
    fetchingForecast: "अंदाज आणला जात आहे…",
    generatingPlan: "तुमची योजना तयार केली जात आहे…",
    severity: "तीव्रता",
    travelAdvisory: "प्रवास सल्ला",
    before: "आधी",
    during: "दरम्यान",
    after: "नंतर",
    checklist: "आपत्कालीन यादी",
    safetyRecommendations: "सुरक्षा शिफारसी",
  },
  Tamil: {
    subtitle: "நிகழ்நேர முன்னறிவிப்பு, உங்கள் மொழியில் AI-தனிப்பயனாக்கப்பட்ட தயார்நிலைத் திட்டங்கள்.",
    city: "நகரம்",
    cityPlaceholder: "எ.கா. மும்பை",
    householdSize: "குடும்ப அளவு",
    language: "மொழி",
    submit: "தயார்நிலைத் திட்டத்தைப் பெறுங்கள்",
    submitting: "உங்கள் திட்டம் தயாராகிறது…",
    fetchingForecast: "முன்னறிவிப்பு பெறப்படுகிறது…",
    generatingPlan: "உங்கள் திட்டம் உருவாக்கப்படுகிறது…",
    severity: "தீவிரம்",
    travelAdvisory: "பயண எச்சரிக்கை",
    before: "முன்பு",
    during: "போது",
    after: "பின்பு",
    checklist: "அவசர பட்டியல்",
    safetyRecommendations: "பாதுகாப்பு பரிந்துரைகள்",
  },
  Telugu: {
    subtitle: "నిజ-సమయ సూచన, మీ భాషలో AI-వ్యక్తిగతీకరించిన సంసిద్ధత ప్రణాళికలు.",
    city: "నగరం",
    cityPlaceholder: "ఉదా. ముంబై",
    householdSize: "కుటుంబ పరిమాణం",
    language: "భాష",
    submit: "సంసిద్ధత ప్రణాళికను పొందండి",
    submitting: "మీ ప్రణాళిక సిద్ధమవుతోంది…",
    fetchingForecast: "సూచన పొందబడుతోంది…",
    generatingPlan: "మీ ప్రణాళిక రూపొందించబడుతోంది…",
    severity: "తీవ్రత",
    travelAdvisory: "ప్రయాణ సలహా",
    before: "ముందు",
    during: "సమయంలో",
    after: "తర్వాత",
    checklist: "అత్యవసర జాబితా",
    safetyRecommendations: "భద్రతా సిఫార్సులు",
  },
  Gujarati: {
    subtitle: "રીઅલ-ટાઇમ આગાહી, તમારી ભાષામાં AI-વ્યક્તિગત તૈયારી યોજનાઓ.",
    city: "શહેર",
    cityPlaceholder: "દા.ત. મુંબઈ",
    householdSize: "કુટુંબનું કદ",
    language: "ભાષા",
    submit: "તૈયારી યોજના મેળવો",
    submitting: "તમારી યોજના તૈયાર થઈ રહી છે…",
    fetchingForecast: "આગાહી મેળવવામાં આવી રહી છે…",
    generatingPlan: "તમારી યોજના બનાવવામાં આવી રહી છે…",
    severity: "તીવ્રતા",
    travelAdvisory: "મુસાફરી સલાહ",
    before: "પહેલાં",
    during: "દરમિયાન",
    after: "પછી",
    checklist: "કટોકટી ચેકલિસ્ટ",
    safetyRecommendations: "સલામતી ભલામણો",
  },
  Kannada: {
    subtitle: "ನೈಜ-ಸಮಯದ ಮುನ್ಸೂಚನೆ, ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ AI-ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸಿದ್ಧತಾ ಯೋಜನೆಗಳು.",
    city: "ನಗರ",
    cityPlaceholder: "ಉದಾ. ಮುಂಬೈ",
    householdSize: "ಕುಟುಂಬದ ಗಾತ್ರ",
    language: "ಭಾಷೆ",
    submit: "ಸಿದ್ಧತಾ ಯೋಜನೆ ಪಡೆಯಿರಿ",
    submitting: "ನಿಮ್ಮ ಯೋಜನೆ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…",
    fetchingForecast: "ಮುನ್ಸೂಚನೆ ಪಡೆಯಲಾಗುತ್ತಿದೆ…",
    generatingPlan: "ನಿಮ್ಮ ಯೋಜನೆ ರಚಿಸಲಾಗುತ್ತಿದೆ…",
    severity: "ತೀವ್ರತೆ",
    travelAdvisory: "ಪ್ರಯಾಣ ಸಲಹೆ",
    before: "ಮೊದಲು",
    during: "ಸಮಯದಲ್ಲಿ",
    after: "ನಂತರ",
    checklist: "ತುರ್ತು ಪಟ್ಟಿ",
    safetyRecommendations: "ಸುರಕ್ಷತಾ ಶಿಫಾರಸುಗಳು",
  },
  Malayalam: {
    subtitle: "തത്സമയ പ്രവചനം, നിങ്ങളുടെ ഭാഷയിൽ AI-വ്യക്തിഗതമാക്കിയ തയ്യാറെടുപ്പ് പദ്ധതികൾ.",
    city: "നഗരം",
    cityPlaceholder: "ഉദാ. മുംബൈ",
    householdSize: "കുടുംബ വലുപ്പം",
    language: "ഭാഷ",
    submit: "തയ്യാറെടുപ്പ് പദ്ധതി നേടുക",
    submitting: "നിങ്ങളുടെ പദ്ധതി തയ്യാറാകുന്നു…",
    fetchingForecast: "പ്രവചനം ലഭിക്കുന്നു…",
    generatingPlan: "നിങ്ങളുടെ പദ്ധതി തയ്യാറാക്കുന്നു…",
    severity: "തീവ്രത",
    travelAdvisory: "യാത്രാ ഉപദേശം",
    before: "മുമ്പ്",
    during: "സമയത്ത്",
    after: "ശേഷം",
    checklist: "അടിയന്തര പട്ടിക",
    safetyRecommendations: "സുരക്ഷാ ശുപാർശകൾ",
  },
  Punjabi: {
    subtitle: "ਰੀਅਲ-ਟਾਈਮ ਪੂਰਵ ਅਨੁਮਾਨ, ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ AI-ਵਿਅਕਤੀਗਤ ਤਿਆਰੀ ਯੋਜਨਾਵਾਂ।",
    city: "ਸ਼ਹਿਰ",
    cityPlaceholder: "ਜਿਵੇਂ ਮੁੰਬਈ",
    householdSize: "ਪਰਿਵਾਰ ਦਾ ਆਕਾਰ",
    language: "ਭਾਸ਼ਾ",
    submit: "ਤਿਆਰੀ ਯੋਜਨਾ ਪ੍ਰਾਪਤ ਕਰੋ",
    submitting: "ਤੁਹਾਡੀ ਯੋਜਨਾ ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ…",
    fetchingForecast: "ਪੂਰਵ ਅਨੁਮਾਨ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…",
    generatingPlan: "ਤੁਹਾਡੀ ਯੋਜਨਾ ਬਣਾਈ ਜਾ ਰਹੀ ਹੈ…",
    severity: "ਗੰਭੀਰਤਾ",
    travelAdvisory: "ਯਾਤਰਾ ਸਲਾਹ",
    before: "ਪਹਿਲਾਂ",
    during: "ਦੌਰਾਨ",
    after: "ਬਾਅਦ",
    checklist: "ਐਮਰਜੈਂਸੀ ਸੂਚੀ",
    safetyRecommendations: "ਸੁਰੱਖਿਆ ਸਿਫ਼ਾਰਸ਼ਾਂ",
  },
  Spanish: {
    subtitle: "Pronóstico en tiempo real, planes de preparación personalizados por IA, en tu idioma.",
    city: "Ciudad",
    cityPlaceholder: "ej. Mumbai",
    householdSize: "Tamaño del hogar",
    language: "Idioma",
    submit: "Obtener plan de preparación",
    submitting: "Preparando tu plan…",
    fetchingForecast: "Obteniendo el pronóstico…",
    generatingPlan: "Generando tu plan…",
    severity: "Gravedad",
    travelAdvisory: "Aviso de viaje",
    before: "Antes",
    during: "Durante",
    after: "Después",
    checklist: "Lista de emergencia",
    safetyRecommendations: "Recomendaciones de seguridad",
  },
  French: {
    subtitle: "Prévisions en temps réel, plans de préparation personnalisés par IA, dans votre langue.",
    city: "Ville",
    cityPlaceholder: "ex. Mumbai",
    householdSize: "Taille du foyer",
    language: "Langue",
    submit: "Obtenir le plan de préparation",
    submitting: "Préparation de votre plan…",
    fetchingForecast: "Récupération des prévisions…",
    generatingPlan: "Génération de votre plan…",
    severity: "Gravité",
    travelAdvisory: "Avis de voyage",
    before: "Avant",
    during: "Pendant",
    after: "Après",
    checklist: "Liste de contrôle d'urgence",
    safetyRecommendations: "Recommandations de sécurité",
  },
};

export function getUiStrings(language: string): UiStrings {
  return UI_STRINGS[language] ?? EN;
}
